[package]
name = "chip-8-emulator-gui-app"
version = "0.1.0"
authors = ["Mikhail Rybakov <me@opilar.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
"chip-8-emulator" = { path = "../emulator" }
sdl2 = "0.33"
